### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by Furtif** [ShuffleDATMT/PTC-Creator#1]
Is possible make this on WindowsForms Mode?

**Comment by ShuffleDATMT** [comment]
Um... I don't like Winform actually especially because of the box UI

**Comment by Furtif** [comment]
if not nedded i not ask... only idee

**Comment by ShuffleDATMT** [comment]
Sorry. I am not sure what you mean...

**Comment by Furtif** [comment]
not worries
