### ISSUE TITLE
Captcha timeout

### ISSUE THREAD

**Issue by Petterholm** [ShuffleDATMT/PTC-Creator#10]
The bot times out on receiving captcha answers a few times is it possible to set this time higher?

**Comment by ShuffleDATMT** [comment]
There is no point of setting it's too high. The official suggestion for time out is 200 seconds and I am using the library official gives. I'd assume you are using Anti-captcha. They work pretty fast, usually returns less than 60 seconds. 

If it's unsolvable or time-out, I don't think they would charge you for anything

**Comment by Petterholm** [comment]
It looks like it is about 20 seconds, had about 200 waiting for captchas and many of them timed out after a short time.

**Comment by ShuffleDATMT** [comment]
https://github.com/ShuffleDATMT/PTC-Creator/blob/de1876e56676280babfb44d82fabb58587b0b748/PTC-Creator/Models/Captchas/AntiCaptcha/AnticaptchaBase.cs#L71

**Comment by Petterholm** [comment]
Mine stops alot earlier then 400

**Comment by ShuffleDATMT** [comment]
https://github.com/ShuffleDATMT/PTC-Creator/blob/master/PTC-Creator/Models/Creation/Creator.cs#L350-L377

There will be two reasons
1. Timeout since no reponse from Anti-Captcha
2. Anticaptcha return excpetion

**Comment by ShuffleDATMT** [comment]
I have tested the problem you mentioned in the issue. The number shows inside the creator perfectly matched up with the amount shows up in the anti-captcha website. Closed

**Comment by ShuffleDATMT** [comment]
969 total captcha shows in the creator and 16 pending.
971 total captcha shows on Anti-captcha website
