### ISSUE TITLE
Captcha error

### ISSUE THREAD

**Issue by Petterholm** [ShuffleDATMT/PTC-Creator#14]
![capture](https://user-images.githubusercontent.com/16854912/37856461-d531dfde-2ef4-11e8-8c7a-bf5d1de86e2f.PNG)
Why do i get alot of these errors, and what do they mean?

**Comment by Petterholm** [comment]
![capture](https://user-images.githubusercontent.com/16854912/37856524-2c776b6a-2ef5-11e8-9871-725bc4f87889.PNG)

**Comment by ShuffleDATMT** [comment]
Please select the row and past the entire message into the chat here. Part of the code is not really useful.
