### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Petterholm** [ShuffleDATMT/PTC-Creator#15]
**IDEA**
Since the pokemon site first blocks you after captcha enter could it be possible to try to create the account before you solve captcha to check if the proxy is banned? Adding a GIF explaining more. 

I **know** it says i have to solve captcha but maybe it bans first?

https://gyazo.com/7dc0559f9f0afadad6381cc6c7a14bf2

**Comment by ShuffleDATMT** [comment]
It's not possible, it will only show captcha needed
