### ISSUE TITLE
Creation freezes after update

### ISSUE THREAD

**Issue by Petterholm** [ShuffleDATMT/PTC-Creator#17]
The creator freesez after first "raid" of threads and doesnt start again
![828683a6-be06-41c7-80dd-4510b82fc55b](https://user-images.githubusercontent.com/16854912/37861796-3ad4a492-2f41-11e8-9407-de8124db6206.png)

**Comment by ShuffleDATMT** [comment]
I will push another version later

**Comment by Petterholm** [comment]
Okay

**Comment by ShuffleDATMT** [comment]
Fixed in 1.0.8.5. If not please reopen this issue

**Comment by Petterholm** [comment]
Still happening

**Comment by ShuffleDATMT** [comment]
How many thread are you using?

**Comment by ShuffleDATMT** [comment]
And how fast are you creating

**Comment by Petterholm** [comment]
50 threads atm, stops after 50 tries. 30/s

**Comment by ShuffleDATMT** [comment]
Why are you saying it freezes. Please scroll down to check logs see whether there are accounts actually processing

**Comment by Petterholm** [comment]
Its not accs being created, it stops creating new threads.

**Comment by ShuffleDATMT** [comment]
Is that what you mean freezes?

**Comment by Petterholm** [comment]
Yea, the thread creator freezes (stops statring new threads)

**Comment by ShuffleDATMT** [comment]
How long have you been waiting

**Comment by Petterholm** [comment]
For 2 hours ago i waited for over an hour

**Comment by ShuffleDATMT** [comment]
Which version are you using?

**Comment by Petterholm** [comment]
Newest

**Comment by ShuffleDATMT** [comment]
I have no problem using the latest one. Tell me more about your proxy settings and your creator settings

**Comment by Petterholm** [comment]
900 rotating proxy threads, running 50 threads atm 30/s.

**Comment by ShuffleDATMT** [comment]
Try the new version. I just tested with your setting, nothing weird. Works perfect for me

**Comment by Lemon2go** [comment]
same here . created 756accs and have been freezes for 30minutes

**Comment by ShuffleDATMT** [comment]
I am going to run a new test

**Comment by ShuffleDATMT** [comment]
No UI updates at all? @Lemon2go

**Comment by ShuffleDATMT** [comment]
Run 1 thread see whether it's generating correctly

**Comment by ShuffleDATMT** [comment]
@Petterholm If you have problem using the new version, use the old version for now

**Comment by ShuffleDATMT** [comment]
Well. I don't know whether it's my problem or not, threads are created correctly but I cant create any account due to proxy problem. I will rework on the logic and publish another version in 24 hours
