### ISSUE TITLE
crash .3 inner exception

### ISSUE THREAD

**Issue by Lemon2go** [ShuffleDATMT/PTC-Creator#19]
1.HttpRequestException: An error occurred while sending the request.
  | Name | Value | Type
-- | -- | -- | --
  | Message | "One or more errors occurred." | string
  | StackTrace | "   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\r\n   at System.Threading.Tasks.Task`1.get_Result()\r\n   at PTC_Creator.Models.Creation.Controller.WebProxyThread() in C:\\Users\\Administrator\\Downloads\\new ptc\\PTC-Creator\\PTC-Creator\\Models\\Creation\\Controller.cs:line 244\r\n   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.ThreadHelper.ThreadStart()" | string

**Comment by Lemon2go** [comment]
2.WebException: Unable to connect to the remote server

  | Name | Value | Type
-- | -- | -- | --
  | Message | "One or more errors occurred." | string
  | StackTrace | "   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\r\n   at System.Threading.Tasks.Task`1.get_Result()\r\n   at PTC_Creator.Models.Creation.Controller.WebProxyThread() in C:\\Users\\Administrator\\Downloads\\new ptc\\PTC-Creator\\PTC-Creator\\Models\\Creation\\Controller.cs:line 244\r\n   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.ThreadHelper.ThreadStart()" | string

**Comment by Lemon2go** [comment]
3.SocketException: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full

  | Name | Value | Type
-- | -- | -- | --
  | Message | "One or more errors occurred." | string
  | StackTrace | "   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\r\n   at System.Threading.Tasks.Task`1.get_Result()\r\n   at PTC_Creator.Models.Creation.Controller.WebProxyThread() in C:\\Users\\Administrator\\Downloads\\new ptc\\PTC-Creator\\PTC-Creator\\Models\\Creation\\Controller.cs:line 244\r\n   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.ThreadHelper.ThreadStart()" | string

**Comment by Lemon2go** [comment]
those issues happened at 1.0.8.5

**Comment by ShuffleDATMT** [comment]
new version pushed please check again. Not sure its fixed
