### ISSUE TITLE
Shuffle captcha not working

### ISSUE THREAD

**Issue by Petterholm** [ShuffleDATMT/PTC-Creator#20]
![capture](https://user-images.githubusercontent.com/16854912/37868529-187427d0-2fa8-11e8-953a-d4223c0b5bec.PNG)
![capture2](https://user-images.githubusercontent.com/16854912/37868530-188acb52-2fa8-11e8-9abc-abb5cc6042d7.PNG)

**Comment by ShuffleDATMT** [comment]
Working good for me

**Comment by Petterholm** [comment]
I were just supposed to put my API into it and activate right? Doesnt work

**Comment by ShuffleDATMT** [comment]
Um... Try again? I don't know, it works on my end tho

**Comment by Petterholm** [comment]
Tried multiple times same thing

**Comment by Benney29** [comment]
Same problem here, shuffle Captcha doesn't work. Always fails/error
![captcha error](https://user-images.githubusercontent.com/36248370/37871462-b649b812-2fee-11e8-972c-028906152246.PNG)

**Comment by ShuffleDATMT** [comment]
@Benney29 works good... This problem is already confirmed solved. It's some weird issue
