### ISSUE TITLE
Creator crashing

### ISSUE THREAD

**Issue by Petterholm** [ShuffleDATMT/PTC-Creator#25]
Newest version crashes every time i start it. Tried on 4 different computers, 2 vps, 1 dedicated server and my own pc. No crash log
![f3184d4b-e59b-495c-b821-2ace4aabca7c](https://user-images.githubusercontent.com/16854912/37898230-8cf0f55c-30e8-11e8-874d-4e23b501d054.png)

**Comment by Lemon2go** [comment]
should be same issue
  | Name | Value | Type
-- | -- | -- | --
  | Message | "Value cannot be null.\r\nParameter name: source" | string
  | StackTrace | "   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)\r\n   at PTC_Creator.Models.Creation.Creator.GetUsername() in C:\\Users\\Administrator\\Downloads\\new ptc\\PTC-Creator\\PTC-Creator\\Models\\Creation\\Creator.cs:line 598\r\n   at PTC_Creator.Models.Creation.Creator.GetRandomAccount() in C:\\Users\\Administrator\\Downloads\\new ptc\\PTC-Creator\\PTC-Creator\\Models\\Creation\\Creator.cs:line 572\r\n   at PTC_Creator.Models.Creation.Creator.Start() in C:\\Users\\Administrator\\Downloads\\new ptc\\PTC-Creator\\PTC-Creator\\Models\\Creation\\Creator.cs:line 28\r\n   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.ThreadHelper.ThreadStart()" | string

**Comment by ShuffleDATMT** [comment]
No log for original bug post, second is duplicated
