### ISSUE TITLE
Success Fails Rate all shows zero but Account already created 

### ISSUE THREAD

**Issue by Lemon2go** [ShuffleDATMT/PTC-Creator#4]
Success Fails Rate all shows zero but Account already created

**Comment by Benney29** [comment]
Same issue, but a very big improvement of the account creator !!!

**Comment by ShuffleDATMT** [comment]
Ok. Let me run it for few hours and see how it will go

**Comment by ShuffleDATMT** [comment]
This should be fix for version v1.0.2
