### ISSUE TITLE
Resolve captcha

### ISSUE THREAD

**Issue by jack1230** [ShuffleDATMT/PTC-Creator#6]
will they implement the option to resolve captcha manually and also add 2captcha?

**Comment by Benney29** [comment]
@jack1230 So far I can see, 2captcha is already added -- "twocaptcha"

**Comment by ShuffleDATMT** [comment]
@jack1230 2Captcha is already been added to the program. I don't think I would consider adding manual solving in this repo. The program was designed for mass creation. Manual solving might give you more trouble besides just creating for PTC accounts.
